fly command

diff --git a/fly b/fly
--- a/fly
+++ b/fly
@@ -26,48 +26,6 @@ type gtar >/dev/null 2>&1 && _fly_tar=gtar || _fly_tar=tar
     _fly_taropts=( --exclude=.git --exclude=.github --exclude=.gitignore )
 } || _fly_taropts=( --no-xattrs --exclude-vcs )
 
-function _fly_usage
-{
-    cat - <<'EOF'
-usage: fly <action> <options>
-$ fly add <gituser/reponame>    # add plugin from github repository
-$ fly del <plugin>              # remove plugin with name <plugin> (repo)
-$ fly update <plugin>           # update plugin from github
-$ fly updateall                 # update all plugins from github
-$ fly source                    # source the plugins for current shell (*.plugin.<shell>)
-$ fly upgrade                   # upgrade fly from github joknarf/thefly
-$ flyls                         # list plugins for current shell
-$ flysh <shell>                 # change current shell with fly env
-$ flyas [<user>] [<shell>]      # change user with your fly env (default <user>: root,<shell>: <user> shell)
-$ flyto <ssh options>           # connect to server through ssh with your fly env
-$ flysuto <user> <ssh options>  # use sudo <user> to connect to server through ssh with your fly env
-
-aliases:
-$ fbash                         # flysh bash
-$ fksh                          # flysh ksh
-$ fzsh                          # flysh zsh
-
-$ fsudo                         # flyas
-$ fsudob                        # flyas with bash
-$ fsudok                        # flyas with ksh
-$ fusdoz                        # flyas with zsh
-
-$ fssh                          # flyto
-$ fsshb                         # flyto with bash
-$ fsshk                         # flyto with ksh
-$ fsshz                         # flyto with zsh
-
-$ fsuto                        # flysuto
-$ fsussh                       # flysuto
-
-# fly environment files:
-~/.fly.d/.flyrc                 # common environment
-~/.fly.d/.bashrc                # specific bash environment
-~/.fly.d/.kshrc                 # specific ksh environment
-~/.fly.d/.zshrc                 # specific zsh environment
-EOF
-}
-
 function _fly_zsh_glob
 {
     [ "${FLY_SHELL##*/}" = "zsh" ] || return 0
@@ -78,14 +36,16 @@ function _fly_zsh_glob
 }
 
 case "$1" in
-    help)
-        _fly_usage
-    ;;
+    help)  cat "$_fly_lib/usage";;
     login)      
         shift 
         echo "$FLY_MSG" >&2
         . "$_fly_lib/.login.${FLY_SHELL##*/}"
         . "$_fly_lib/.source_plugins"
+        [ "$_fly_cmd" ] && {
+          [ "$ZSH_VERSION" ] && setopt SH_WORD_SPLIT
+          eval "$_fly_cmd" ; exit $?;
+        }
         unset _fly_destshell FLY_ETC_RC FLY_USER_RC
     ;;
     loginshell|install)
@@ -174,8 +134,10 @@ function _fly_xpackage
 function _fly_sudo
 {
     typeset user="${1:-root}"
+    [ "$user" = '-' ] && user='root'
+    shift
     \cd /
-    sudo -Hu "$user" '/bin/sh' <<<"$(_fly_pkg_warp)"
+    sudo -Hu "$user" '/bin/sh' <<<"$(_fly_pkg_warp "$@")"
     \cd "$OLDPWD"
 }
 
@@ -217,6 +179,7 @@ function _fly_pkg_login
 _fly_destshell="$_fly_destshell"
 FLY_ETC_RC="${FLY_ETC_RC:-true}"
 FLY_USER_RC="${FLY_USER_RC:-true}"
+export _fly_cmd="$([ "$1" ] && printf '%q ' "$@")"
 . "\$FLY_HOME/.fly.d/.fly.lib/.loginshell"
 EOF
 }
@@ -225,36 +188,38 @@ function _fly_pkg_warp
 {
     cat - <<EOF
 $(_fly_package_zfx)
-$(_fly_pkg_login)
+$(_fly_pkg_login "$@")
 EOF
 }
 
 function _fly_ssh
 {
-    ! $_fly_ssh_ok && { _fly_ssh2 "$@"; return $?; } 
-    typeset ssh_config cmd c i
-    cmd="exec /bin/sh -c '$(_fly_pkg_warp)'"
-    [ ${#cmd} -gt 130000 ] && { _fly_ssh2 "$@"; return $?; }
-    for i in "$@";do
-       [ "$i" = -F ] && shift && c=1 && continue
-       [ "$c" ] && unset c && ssh_config="Include $i" && shift && continue
-       shift
-       set -- "$@" "$i"
+    typeset cmd ssh_args=() ssh_config ssh_argc=()
+    while [ "$1" ];do
+        [ "$1" = -F ] && shift && ssh_config="Include $1" && ssh_argc=(-F "$1") && shift && continue
+        [ "$1" = -- ] && shift && fly_cmd=("$@") && break
+        ssh_args+=("$1")
+        shift
     done
-    [ ! "$ssh_config" ] && [ -f ~/.ssh/config ] && ssh_config="Include $HOME/.ssh/config"
+    cmd="exec /bin/sh -c '$(_fly_pkg_warp "${fly_cmd[@]}")'"
     cmd="${cmd//$'\n'/;}"
+    ! $_fly_ssh_ok && { _fly_ssh2 "${ssh_args[@]}" "${ssh_argc[@]}"; return $?; } 
+    [ ${#cmd} -gt 130000 ] && { _fly_ssh2 "${ssh_args[@]}" "${ssh_argc[@]}"; return $?; }
+    [ ! "$ssh_config" ] && [ -f ~/.ssh/config ] && ssh_config="Include $HOME/.ssh/config"
     cat - <<_EOF_ >"$FLY_HOME/.fly.ssh"
 RequestTTY yes
 RemoteCommand $cmd
 $ssh_config
 _EOF_
-    \cd $FLY_HOME;ssh -F .fly.ssh "$@";\cd $OLDPWD
+    \cd "$FLY_HOME";ssh -F .fly.ssh "${ssh_args[@]}";\cd "$OLDPWD"
+    unset fly_cmd
 }
 
 function _fly_ssh2
 {
     _fly_package | ssh -o LogLevel=Error "$@" "/bin/sh -c '$(_fly_xpretar);$(_fly_xpackage)'" || return $?
-    ssh "$@" -t "exec /bin/sh -c 'FLY_HOME=\"$_fly_tmpdir\";$(_fly_pkg_login)'"
+    ssh "$@" -t "exec /bin/sh -c 'FLY_HOME=\"$_fly_tmpdir\";$(_fly_pkg_login "${fly_cmd[@]}")'"
+    unset fly_cmd
 }
 
 function _fly
@@ -282,9 +247,8 @@ function _fly
         ;;
         sudo|as) 
             shift;
-            [ "$2" ] && ! type "$2" >/dev/null 2>&1 && echo "Cannot find shell $2" >&2 && return 1
-            _fly_destshell="${2:-$_fly_destshell}"
-            _fly_sudo "$1"
+            [ "$_fly_destshell" ] && ! type "$_fly_destshell" >/dev/null 2>&1 && echo "Cannot find shell $2" >&2 && return 1
+            _fly_sudo "$@"
         ;;
         pack)
             shift
@@ -295,9 +259,7 @@ function _fly
     unset _fly_destshell
 }
 
-unset -f _fly_usage
 [ "$_fly_lock" ] && trap - TERM && flock -u 4 && exec 4<&- # unlock teleportation
-unset _fly_lock
 [ "$_fly_share" ] && trap "flock -n 5 && flock '$_fly_share/.fly.lock' rm -rf '$_fly_share'/.fly.* && rmdir '$_fly_share' '${_fly_share%/*}' 2>/dev/null" EXIT
-unset _fly_share
+unset _fly_share _fly_lock
 :
